-- MySQL Script generated by MySQL Workbench
-- Tue May 24 20:55:17 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kbps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kbps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kbps` DEFAULT CHARACTER SET utf8 ;
USE `kbps` ;

-- -----------------------------------------------------
-- Table `kbps`.`disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`disease` (
  `Management` VARCHAR(1024) NULL,
  `Name` VARCHAR(128) NOT NULL,
  `Epidemiology` VARCHAR(1024) NULL,
  `Category` VARCHAR(128) NULL,
  `ID` INT NOT NULL,
  `Description` VARCHAR(1024) NULL,
  `Causes` VARCHAR(1024) NULL,
  `Diagnosis` VARCHAR(1024) NULL,
  `Mechanism` VARCHAR(1024) NULL,
  `Prognosis` VARCHAR(1024) NULL,
  `Prevention` VARCHAR(1024) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`medicine` (
  `Name` VARCHAR(128) NOT NULL,
  `Category` VARCHAR(128) NULL,
  `Description` VARCHAR(1024) NULL,
  `ID` INT NOT NULL,
  `Property` VARCHAR(1024) NULL,
  `Adverse_effect` VARCHAR(1024) NULL,
  `Pharmacokinetics` VARCHAR(1024) NULL,
  `Mechanism` VARCHAR(1024) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`symptom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`symptom` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(128) NOT NULL,
  `Category` VARCHAR(128) NULL,
  `Description` VARCHAR(1024) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`Incompatibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`Incompatibility` (
  `medicine ID` INT NOT NULL,
  `medicine_ID2` INT NOT NULL,
  PRIMARY KEY (`medicine ID`, `medicine_ID2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`doctor` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(128) NOT NULL,
  `Gender` CHAR(1) NOT NULL,
  `Specialty` VARCHAR(128) NULL,
  `Phone` VARCHAR(32) NULL,
  `Age` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`patient` (
  `Gender` CHAR(1) NOT NULL,
  `Phone` VARCHAR(32) NULL,
  `Name` VARCHAR(128) NOT NULL,
  `Age` INT NOT NULL,
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`prescription` (
  `Date` DATE NOT NULL,
  `Content` VARCHAR(1024) NULL,
  `ID` INT NOT NULL,
  `doctor_ID` INT NOT NULL,
  `patient_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_prescription_doctor1_idx` (`doctor_ID` ASC),
  INDEX `fk_prescription_patient1_idx` (`patient_ID` ASC),
  CONSTRAINT `fk_prescription_doctor1`
    FOREIGN KEY (`doctor_ID`)
    REFERENCES `kbps`.`doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_patient1`
    FOREIGN KEY (`patient_ID`)
    REFERENCES `kbps`.`patient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`dise_med`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`dise_med` (
  `disease_ID` INT NOT NULL,
  `medicine_ID` INT NOT NULL,
  PRIMARY KEY (`disease_ID`, `medicine_ID`),
  INDEX `fk_disease_has_medicine_medicine1_idx` (`medicine_ID` ASC),
  INDEX `fk_disease_has_medicine_disease_idx` (`disease_ID` ASC),
  CONSTRAINT `fk_disease_has_medicine_disease`
    FOREIGN KEY (`disease_ID`)
    REFERENCES `kbps`.`disease` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_has_medicine_medicine1`
    FOREIGN KEY (`medicine_ID`)
    REFERENCES `kbps`.`medicine` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`dise_symp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`dise_symp` (
  `disease_ID` INT NOT NULL,
  `symptom_ID` INT NOT NULL,
  PRIMARY KEY (`disease_ID`, `symptom_ID`),
  INDEX `fk_disease_has_symptom_symptom1_idx` (`symptom_ID` ASC),
  INDEX `fk_disease_has_symptom_disease1_idx` (`disease_ID` ASC),
  CONSTRAINT `fk_disease_has_symptom_disease1`
    FOREIGN KEY (`disease_ID`)
    REFERENCES `kbps`.`disease` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_has_symptom_symptom1`
    FOREIGN KEY (`symptom_ID`)
    REFERENCES `kbps`.`symptom` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`symp_presc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`symp_presc` (
  `prescription_ID` INT NOT NULL,
  `symptom_ID` INT NOT NULL,
  PRIMARY KEY (`prescription_ID`, `symptom_ID`),
  INDEX `fk_prescription_has_symptom_symptom1_idx` (`symptom_ID` ASC),
  INDEX `fk_prescription_has_symptom_prescription1_idx` (`prescription_ID` ASC),
  CONSTRAINT `fk_prescription_has_symptom_prescription1`
    FOREIGN KEY (`prescription_ID`)
    REFERENCES `kbps`.`prescription` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_has_symptom_symptom1`
    FOREIGN KEY (`symptom_ID`)
    REFERENCES `kbps`.`symptom` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`presc_med`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`presc_med` (
  `prescription_ID` INT NOT NULL,
  `medicine_ID` INT NOT NULL,
  `medicine_medicine_ID` INT NOT NULL,
  PRIMARY KEY (`prescription_ID`, `medicine_ID`, `medicine_medicine_ID`),
  INDEX `fk_prescription_has_medicine_medicine1_idx` (`medicine_ID` ASC, `medicine_medicine_ID` ASC),
  INDEX `fk_prescription_has_medicine_prescription1_idx` (`prescription_ID` ASC),
  CONSTRAINT `fk_prescription_has_medicine_prescription1`
    FOREIGN KEY (`prescription_ID`)
    REFERENCES `kbps`.`prescription` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_has_medicine_medicine1`
    FOREIGN KEY (`medicine_ID`)
    REFERENCES `kbps`.`medicine` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`dise_presc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`dise_presc` (
  `prescription_ID` INT NOT NULL,
  `disease_ID` INT NOT NULL,
  PRIMARY KEY (`prescription_ID`, `disease_ID`),
  INDEX `fk_prescription_has_disease_disease1_idx` (`disease_ID` ASC),
  INDEX `fk_prescription_has_disease_prescription1_idx` (`prescription_ID` ASC),
  CONSTRAINT `fk_prescription_has_disease_prescription1`
    FOREIGN KEY (`prescription_ID`)
    REFERENCES `kbps`.`prescription` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_has_disease_disease1`
    FOREIGN KEY (`disease_ID`)
    REFERENCES `kbps`.`disease` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`symp_med`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`symp_med` (
  `medicine_ID` INT NOT NULL,
  `medicine_medicine_ID` INT NOT NULL,
  `symptom_ID` INT NOT NULL,
  PRIMARY KEY (`medicine_ID`, `medicine_medicine_ID`, `symptom_ID`),
  INDEX `fk_medicine_has_symptom_symptom1_idx` (`symptom_ID` ASC),
  INDEX `fk_medicine_has_symptom_medicine1_idx` (`medicine_ID` ASC, `medicine_medicine_ID` ASC),
  CONSTRAINT `fk_medicine_has_symptom_medicine1`
    FOREIGN KEY (`medicine_ID`)
    REFERENCES `kbps`.`medicine` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicine_has_symptom_symptom1`
    FOREIGN KEY (`symptom_ID`)
    REFERENCES `kbps`.`symptom` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kbps`.`incompatibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kbps`.`incompatibility` (
  `medicine_ID` INT NOT NULL,
  `medicine_ID1` INT NOT NULL,
  PRIMARY KEY (`medicine_ID`, `medicine_ID1`),
  INDEX `fk_medicine_has_medicine_medicine2_idx` (`medicine_ID1` ASC),
  INDEX `fk_medicine_has_medicine_medicine1_idx` (`medicine_ID` ASC),
  CONSTRAINT `fk_medicine_has_medicine_medicine1`
    FOREIGN KEY (`medicine_ID`)
    REFERENCES `kbps`.`medicine` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicine_has_medicine_medicine2`
    FOREIGN KEY (`medicine_ID1`)
    REFERENCES `kbps`.`medicine` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
